// localStorage es cache local; api.php conserva la copia compartida en JSON.
const STORAGE_KEY="docuraceData";
const EMBEDDED_DATA={players:{},scores:{}};
const readData=()=>{try{return JSON.parse(localStorage.getItem(STORAGE_KEY)||JSON.stringify(EMBEDDED_DATA))}catch{return {players:{},scores:{}}}};
const remoteEnabled=location.protocol!=="file:";
let remoteQueue=Promise.resolve();
const persistLocal=d=>localStorage.setItem(STORAGE_KEY,JSON.stringify(d));
const syncRemote=d=>{if(!remoteEnabled)return;remoteQueue=remoteQueue.then(()=>fetch("api.php",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(d)})).catch(err=>console.warn("No se pudo sincronizar el JSON remoto:",err))};
const writeData=d=>{persistLocal(d);syncRemote(d)};
const loadRemoteData=async()=>{if(!remoteEnabled)return;try{const response=await fetch("api.php",{cache:"no-store"});if(!response.ok)throw new Error(`HTTP ${response.status}`);const remote=await response.json();const local=readData();const remoteHasData=Object.keys(remote?.players||{}).length||Object.keys(remote?.scores||{}).length;const localHasData=Object.keys(local.players||{}).length||Object.keys(local.scores||{}).length;if(remoteHasData){persistLocal({players:remote.players||{},scores:remote.scores||{}})}else if(localHasData){syncRemote(local)}}catch(err){console.warn("Se usará la copia local:",err)}};
window.docuRaceReady=loadRemoteData();
const savePlayerData=(code,data)=>{const d=readData();d.players[code]=data;writeData(d)};
const getPlayerData=code=>readData().players[code]||null;
const getAllPlayers=()=>Object.entries(readData().players||{}).map(([code,player])=>({code,...player}));
const updatePlayerName=(code,name)=>{const d=readData();if(!d.players?.[code])return false;d.players[code].name=name;d.scores=d.scores||{};if(d.scores[code])d.scores[code].name=name;writeData(d);return true};
const deletePlayer=(code)=>{const d=readData();if(!d.players?.[code])return false;delete d.players[code];if(d.scores)delete d.scores[code];writeData(d);return true};
const $=id=>document.getElementById(id),shuffle=a=>[...a].sort(()=>Math.random()-.5),escapeHtml=s=>String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[m]));
const entities=[["Soluciones del Valle S.A.C.","Av. Los Cedros N.° 145","Moquegua"],["Editorial Prisma Sur E.I.R.L.","Jr. Independencia N.° 318","Arequipa"],["Centro Cultural Aurora","Calle Las Flores N.° 72","Tacna"],["Comercial Andina del Pacífico S.R.L.","Av. Mariscal Castilla N.° 510","Ilo"],["Fundación Horizonte Abierto","Jr. Unión N.° 204","Cusco"],["Servicios Logísticos Altamar S.A.C.","Av. Costanera N.° 640","Puno"],["Asociación Cultural Nexo","Calle Mercurio N.° 91","Lima"]];
const names=["Valeria Torres","Martín Salcedo","Camila Rivera","Diego Paredes","Lucía Herrera","Andrés Campos","Sofía Navarro","Renato Vargas","Elena Rojas","Mateo Cárdenas","Paula Méndez","Bruno Castillo","Nadia Ferrer","Tomás Velasco","Marina Quiroz"];
const greetings=["De mi consideración:","Estimado señor:","Apreciada señora:","Señor Director:","Distinguida señora:"];const closures=["Agradezco la atención que se sirva brindar a la presente.","Quedo atento(a) a su respuesta.","Sin otro particular, agradezco su atención.","Hago propicia la ocasión para saludarle cordialmente."];const topics=[["la reserva de una sala para una jornada de capacitación","la actividad requiere proyector y espacio para trabajo en equipo"],["la autorización para utilizar material audiovisual en una exposición","el recurso facilitará la presentación de los contenidos previstos"],["la confirmación de recepción de una propuesta comercial","el envío contiene la ficha técnica y la cotización solicitada"],["la entrega de copias de documentación para un trámite","los documentos son necesarios para completar el expediente"],["la coordinación de una reunión de seguimiento","la reunión permitirá revisar avances y pendientes del proyecto"]];
const categories={cartas:{title:"Cartas",icon:"💌",parts:["Membrete","Lugar y fecha","Destinatario","Asunto","Saludo","Párrafo 1","Párrafo 2","Párrafo 3","Antefirma","Firma","Postfirma","Pie de página"],guide:"La carta formal organiza membrete, fecha, destinatario, asunto, saludo, tres párrafos de cuerpo, antefirma, firma, postfirma y pie de página. En bloque extremo todo parte del margen izquierdo; en bloque y semibloque la fecha, antefirma, firma y postfirma parten desde la mitad hacia la derecha."},solicitudes:{title:"Solicitudes",icon:"📝",parts:["Sumilla","Destinatario","Datos del solicitante","Petitorio","Fundamentos","Lugar y fecha","Firma"],guide:"La solicitud organiza claramente la sumilla, autoridad destinataria, datos del solicitante, pedido, fundamentos, fecha y firma."},memorandos:{title:"Memorandos",icon:"📌",parts:["Membrete","Código","Fecha","Para","De","Asunto","Cuerpo","Despedida","Firma"],guide:"El memorando es una comunicación interna que identifica código, fecha, destinatario, remitente, asunto, mensaje y firma."},actas:{title:"Actas",icon:"📋",parts:["Encabezado","Número de acta","Fecha, hora y lugar","Participantes","Orden del día","Desarrollo","Acuerdos y acciones","Cierre","Firmas"],guide:"El acta registra una reunión: cabecera, participantes, orden del día, desarrollo, decisiones o acciones, cierre y firmas."},institucionales:{title:"Institucionales",icon:"🏛️",parts:["Membrete","Numeración","Lugar y fecha","Destinatario","Asunto","Referencia","Cuerpo","Despedida","Firma y sello","Copias"],guide:"Los documentos institucionales pueden incorporar numeración, asunto, referencia, cuerpo, firma, sello y copias según el caso."}};
const state={player:{name:"",code:""},profile:{categories:{},totalScore:0,coins:20,current:null},category:"",match:1,level:0,levels:[],parts:[],slots:[],score:0,round:0,attempts:3,coins:20,startCoins:20,correct:0,total:0,dirty:0,lastHint:null,timer:null,startedAt:0,verified:false};let drag=null;
function codeForName(){for(let i=0;i<100;i++){const letters="ABCDEFGHJKLMNPQRSTUVWXYZ";const code=`DOC-${letters[Math.floor(Math.random()*letters.length)]}${letters[Math.floor(Math.random()*letters.length)]}${Math.floor(10+Math.random()*90)}`;if(!getPlayerData(code))return code}throw new Error("No se pudo generar un código disponible")}
function localProfiles(){try{return JSON.parse(localStorage.getItem("docuraceProfiles")||"[]")}catch{return[]}}function saveLocal(p){localStorage.setItem("docuraceProfiles",JSON.stringify(p))}function renderProfiles(){const b=$("profileGrid");b.innerHTML="";localProfiles().slice(-8).reverse().forEach(p=>{const x=document.createElement("button");x.className="profileBtn";x.textContent=`👤 ${p.name} · ${p.code}`;x.onclick=()=>{$("playerName").value=p.name;$('playerCode').value=p.code};b.appendChild(x)})}
function createPlayer(name){let ps=localProfiles(),old=ps.find(p=>p.name.toLowerCase()===name.toLowerCase()),code=old?.code||codeForName();state.player={name,code};if(!old){ps.push(state.player);saveLocal(ps)}if(!getPlayerData(code))savePlayerData(code,{name,code,progress:{categories:{},totalScore:0,coins:20,current:null},updatedAt:Date.now()});loadPlayer(code)}
function loadPlayer(code){code=code.trim().toUpperCase();const d=getPlayerData(code);if(!d){alert("No encontré ese código. Revisa que esté escrito correctamente.");return false}state.player={name:d.name||"Jugador",code};state.profile=Object.assign({categories:{},totalScore:0,coins:20,current:null},d.progress||{});state.profile.categories=state.profile.categories||{};state.coins=Number(state.profile.coins??20);saveLocal([...localProfiles().filter(p=>p.code!==code),state.player]);localStorage.setItem("docuraceLastPlayer",JSON.stringify(state.player));return true}
function saveProgress(){if(!state.player.code)return;state.profile.totalScore=Number(state.profile.totalScore||0);state.profile.coins=state.coins;state.profile.current={category:state.category,match:state.match,level:state.level,parts:state.parts,slots:state.slots,score:state.score,coins:state.coins,round:state.round,dirty:state.dirty,verified:state.verified,correct:state.correct,total:state.total,attempts:state.attempts};savePlayerData(state.player.code,{name:state.player.name,progress:state.profile,updatedAt:Date.now()})}
function clearCurrent(){state.profile.current=null;savePlayerData(state.player.code,{name:state.player.name,progress:state.profile,updatedAt:Date.now()})}
function saveScore(){const d=readData();d.scores[state.player.code]={name:state.player.name,score:Number(state.profile.totalScore||0),coins:state.coins,category:state.category,match:state.match,updatedAt:Date.now()};writeData(d)}
function loadRanking(){try{const a=Object.values(readData().scores||{});a.sort((x,y)=>(y.score||0)-(x.score||0));$("ranking").innerHTML=a.slice(0,8).map((x,i)=>`<div>${i+1}. ${escapeHtml(x.name)} <span style="float:right">${x.score||0}</span></div>`).join("")||"<p>Aún no hay puntajes.</p>"}catch{$("ranking").textContent="No se pudo cargar el ranking local."}}
